### ISSUE TITLE
Deletion of goods should be supplier specific

### ISSUE THREAD

**Issue by jialegitgud** [AY2425S1-CS2103-F10-1/tp#110]
Current deletion logic allows deletion via goods name. Hence, if `Bread` has been supplied by two suppliers, `deletegoods gn/Bread` will result in both suppliers records being deleted. As such, delete goods should consider both goods name and supplier name to ensure data integrity.

**Comment by yanhwee** [comment]
I suppose I can work on this. Proposed solution is to not use preamble and use two prefix arguments, of PREFIX_NAME and PREFIX_GOODS_NAME.
