### ISSUE TITLE
Deleting of Suppliers should use Name Prefix.

### ISSUE THREAD

**Issue by jialegitgud** [AY2425S1-CS2103-F10-1/tp#111]
Helps to ensure the consistency of command formats throughout the app, and make it more intuitive for the user.

**NOTE:** JavaDoc in DeleteCommand should also be fixed to reflect expected behaviour.

**Comment by yanhwee** [comment]
Hmm. I am not sure if this is a consistency issue. The edit command follows the same format as well. I suppose that some commands will have this "preamble" field without prefix. Prefixes are for additional information?
