### ISSUE TITLE
Delete goods missing error message when inputting a name but no goods name

### ISSUE THREAD

**Issue by ossaris56** [AY2425S1-CS2103-F10-1/tp#137]
An error message is correctly displayed when the supplier name is missing (e.g., `deletegoods n/ gn/Bread`), but this does not happen when the supplier name is provided and the goods name is left blank (e.g., `deletegoods n/Alex gn/`)

**Comment by yanhwee** [comment]
I can't replicate it on the latest master.

**Comment by yanhwee** [comment]
The error message for empty supplier name is the same as empty goods name. I guess I will update the empty goods name error to be different.
