### ISSUE TITLE
Adding goods with a future dated procurement date causes runtime error 

### ISSUE THREAD

**Issue by ossaris56** [AY2425S1-CS2103-F10-1/tp#138]
e.g. `addgoods gn/Gardenia Milk Bread q/2 p/5 c/CONSUMABLES pd/2025-08-08 11:00 ad/2025-11-11 11:00 n/Alex Yeoh`

Causes a InvocationTargetException without any feedback in the UI.

**Comment by yanhwee** [comment]
Fixed together in PR #150.
