### ISSUE TITLE
Delivered goods will not be marked automatically

### ISSUE THREAD

**Issue by jialegitgud** [AY2425S1-CS2103-F10-1/tp#162]
If the arrival date has already passed, the goods will remain marked as "undelivered".

Should be handled only in two scenarios for convenience:
* on startup of the application
* when viewgoods is called

**Comment by yanhwee** [comment]
I suggest that the delivery status should not be stored as an attribute. Rather to "get" the delivery status of a goods, one must call a function `isDelivered()`. The delivery status will be computed by checking the arrival date against the current time.
