### ISSUE TITLE
[PE-D][Tester A] The title of the application when launching GUI should be the name of the application

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2103-F10-1/tp#174]
![image.png](https://raw.githubusercontent.com/awdse22/ped/main/files/ab9437e5-4523-4ec3-b19b-179190eddac8.png)

Currently the name of the application at the top left corner of the GUI states `Address App`, which is the same as the original AB3. This can be changed to `Supply Central` so it's less confusing for the user.

-------------
Labels: `severity.VeryLow` `type.FunctionalityBug`
original: awdse22/ped#1

**Comment by thenosewizard** [comment]
Can be fixed

**Comment by jialegitgud** [comment]
Duplicate of #192

**Comment by jialegitgud** [comment]
Resolved.
