### ISSUE TITLE
[PE-D][Tester A] Table of contents does not load properly in user guide PDF

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2103-F10-1/tp#175]
![image.png](https://raw.githubusercontent.com/awdse22/ped/main/files/5a197ebc-f168-485e-88d6-9b9ca5d46a8c.png)

In the user guide pdf, the table of contents is visually written as

* Table of Contents
  {:toc}

Perhaps this should either be displayed properly or removed so it doesn't confuse the readers of the user guide?

-------------
Labels: `severity.Low` `type.DocumentationBug`
original: awdse22/ped#2

**Comment by thenosewizard** [comment]
UG/DG bug
