### ISSUE TITLE
[PE-D][Tester B] `viewgoods` input validation

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2103-F10-1/tp#182]
Input: `viewgoods apple`
Expected: Maybe should tell the user that their command format is invalid instead of treating it as `viewgoods`, since the intention of the user typing in a second word is most likely to be searching by that keyword.
Actual: Whole list appears.

-------------
Labels: `severity.Low` `type.FunctionalityBug`
original: beginner-web-developer/ped#2

**Comment by jialegitgud** [comment]
Might actually be a functionality bug, as it is explicitly stated in UG that we should be only taking marked filters.

Expected behaviour should be the error message.
