### ISSUE TITLE
[PE-D][Tester A] Use cases in developer guide uses postcondition instead of guarantees

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2103-F10-1/tp#200]
![image.png](https://raw.githubusercontent.com/awdse22/ped/main/files/15256cf5-5e65-4614-9bea-98d2809dd2b7.png)

In the user guide, for each use case, the precondition and postconditions are stated.
However, based on the CS2103 notes, shouldn't `postcondition` be labelled as `guarantees` instead?

![image.png](https://raw.githubusercontent.com/awdse22/ped/main/files/7f5121d4-784b-4ca7-9ad0-1ae8e5659f9d.png)

-------------
Labels: `severity.VeryLow` `type.DocumentationBug`
original: awdse22/ped#13

**Comment by thenosewizard** [comment]
UG/DG bug (??)
