### ISSUE TITLE
[PE-D][Tester B] Specifying categories

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2103-F10-1/tp#201]
It may be time consuming for the user to purposely capitalise the categories. Can consider allowing for lower case categories to be accepted as well, e.g. `viewgoods c/consumables`

-------------
Labels: `severity.Low` `type.FeatureFlaw`
original: beginner-web-developer/ped#6

**Comment by ossaris56** [comment]
Can specify in the UG that goods categories must be fully capitalized. Also can add to planned enhancements to allow this feature.
