### ISSUE TITLE
[PE-D][Tester B] NFRs not scoped clearly

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2103-F10-1/tp#207]
I feel that NFRS 4, 10, 12 are quite subjective, and difficult to ensure when it has been met. They may not be necessary as well.

-------------
Labels: `severity.Low` `type.DocumentationBug`
original: beginner-web-developer/ped#8

**Comment by jialegitgud** [comment]
Should be removed from DG.
