### ISSUE TITLE
[PE-D][Tester A] Arrival time can be the same as procurement time

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2103-F10-1/tp#214]
![image.png](https://raw.githubusercontent.com/awdse22/ped/main/files/a3e4de35-d18e-499d-9801-f7490b609537.png)

The arrival time can be the same as procurement time when adding goods.

Example command:
addgoods gn/Apple q/10 p/10 c/CONSUMABLES pd/2002-01-01 11:00 ad/2002-01-01 11:00 n/David Li

-------------
Labels: `severity.Low` `type.FunctionalityBug`
original: awdse22/ped#18

**Comment by thenosewizard** [comment]
This would require a behaviour enhancement. Thus, should be under UG/DG (?)
