### ISSUE TITLE
[PE-D][Tester D] Broken Links in DG

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2103-F10-1/tp#219]
![image.png](https://raw.githubusercontent.com/currynia/ped/main/files/33f0d373-20eb-4a6b-8101-47614e411c2e.png)

This part at the beginning of the developer guide has a broken link.

-------------
Labels: `severity.High` `type.DocumentationBug`
original: currynia/ped#6

**Comment by ossaris56** [comment]
Don't think this needs to be fixed as per the "What to do with other dev docs" in the [tp deliverables](https://nus-cs2103-ay2425s1.github.io/website/admin/tp-deliverables.html#deliverable-developer-guide-dg).
