### ISSUE TITLE
[PE-D][Tester A] UI elements should have a limit in resizing

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2103-F10-1/tp#235]
![image.png](https://raw.githubusercontent.com/awdse22/ped/main/files/53297e19-a19c-4966-bf72-64896f0b019c.png)
![image.png](https://raw.githubusercontent.com/awdse22/ped/main/files/01df93c0-441b-4f86-9b13-2721496f85a6.png)

Currently there is no limit and each UI element can be as small as possible, to a point where it may not be visible at all. In a case where the user does this by accident, the user may be confused about the UI element, so there should be a minimum height/width for each UI element.

-------------
Labels: `severity.Low` `type.FunctionalityBug`
original: awdse22/ped#21

**Comment by thenosewizard** [comment]
UG/DG bug
