### ISSUE TITLE
[PE-D][Tester A] Duplicate detection for tags is case sensitive

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2103-F10-1/tp#237]
![image.png](https://raw.githubusercontent.com/awdse22/ped/main/files/df7a8398-a39f-4a04-b602-aa0b518683fe.png)

Tags can have different casing and be detected as different tags.

-------------
Labels: `severity.Low` `type.FunctionalityBug`
original: awdse22/ped#23

**Comment by thenosewizard** [comment]
Not specified in the UG/DG. Thus can be placed under feature enhancements
